name: game
description: A Flutter project for a game.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: '>=3.0.0-348.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  
  #Navigation
  auto_route: ^5.0.3
  

  #UI
  google_fonts: ^4.0.4
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.7
  spider: ^4.2.1
  loading_animation_widget: ^1.2.0+4
  ionicons: ^0.2.2


  #DI
  get_it: ^7.2.0
  injectable: ^1.5.3


  #Firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.0
  google_sign_in: ^6.0.2


  #Rest
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  uuid: ^3.0.7
  connectivity_plus: ^4.0.1
  email_validator: ^2.1.17
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.2
  

  #Utils
  logger: ^1.3.0


  #Bloc
  flutter_bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  auto_route_generator: ^5.0.3
  injectable_generator: ^1.5.4
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/

flutter_native_splash:
  color: "#0B9933"
  image: "assets/images/splash-icon.png"
  fullscreen: true

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/logo-background.png" 
  adaptive_icon_foreground: "assets/images/logo-foreground.png"
  min_sdk_android: 21